### ISSUE TITLE
Unable to start the GUI due to Pyro

### ISSUE THREAD

**Issue by TheNetworker** [rsm-gh/alienware-kbl#35]
# System information
```shell
bassim@me-inside:~$ sudo  setsid alienware-kbl --start-daemon
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xe0 Self Powered, Remote Wakeup
   bMaxPower            :    0x0 (0 mA)
    INTERFACE 0: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x81: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :    0xa (10 bytes)
       bInterval        :    0xa


    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=TX
    description=Tact-X
    hex_id=8192
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=TP
    description=Touchpad
    hex_id=1024
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


DEBUG from `/usr/share/AlienwareKBL/Configuration/Theme.py` on method `load`:
path=`/root/.local/share/alienware-kbl/Default.cfg`


area=RS


mode=fixed
left_color=#0000FF
right_color=#0000FF

********************************************   
area=TP                


mode=fixed             
left_color=#0000FF     
right_color=#0000FF    

********************************************   
area=TX                


mode=fixed             
left_color=#0000FF     
right_color=#0000FF    


+ Distribution name: Ubuntu
+ Distribution version: Ubuntu 17.10
+ Python version: 3.6.6
+ Computer model: AW 15R3
+ Output of the command `alienware-kbl --daemon-is-on`: TRUE
```
# Bug description

Dears,
I'm unable to start the GUI after installing the packages. Also the pyro package can't be installed on the system and the below error is thrown each time I start Ubuntu
 
![selection_007](https://user-images.githubusercontent.com/11037464/32684380-a6702a88-c68b-11e7-9e54-e5a3dc64ace6.png)

![selection_007](https://user-images.githubusercontent.com/11037464/32684486-a2f20b78-c68c-11e7-92d0-8bb5e8f9a68f.png)

```shell
bassim@me-inside:~$ pip3 install pyro
Collecting pyro
  Using cached Pyro-3.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6fyolzqa/pyro/setup.py", line 23
        exec code in constants
                ^
    SyntaxError: Missing parentheses in call to 'exec'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6fyolzqa/pyro/
bassim@me-inside:~$  `
```

**Comment by Hexedheart** [comment]
I actually JUST fixed this issue myself. 
try 'pip3 install pyro4==4.46'
pyro4.47+ doesn't work correctly as some things were changed(as stated in the install instructions) and this will force pip to install pyro 4.46 instead

**Comment by TheNetworker** [comment]
Thanks @Hexedheart . This fix my problem. However the KBL still not started and give error "'Configuration.Computers' has no attribute 'Alienware 15R3"


```bash
bassim@me-inside:~$ alienware-kbl     

(GUI.py:6501): Gtk-WARNING **: Unknown type < define a new column > specified in treemodel liststore_default_blocks

(GUI.py:6501): Gtk-WARNING **: /build/gtk+3.0-Th_a5U/gtk+3.0-3.22.24/./gtk/gtkliststore.c:516: Invalid type (null)

(GUI.py:6501): Gtk-WARNING **: Allocating size to GtkScrolledWindow 0x17d26d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/ADDONS/GUI/GUI.py", line 736, in <module>
    gui = GUI()
  File "/usr/share/AlienwareKBL/ADDONS/GUI/GUI.py", line 244, in __init__
    self.computer = getattr(Computer, computer_name)()
AttributeError: module 'Configuration.Computers' has no attribute 'Alienware 15R3'```

**Comment by TheNetworker** [comment]
I fixed my own issue in previous command by modifying the file GUI.py and pass the computer_name as a static value
```vim /usr/share/AlienwareKBL/ADDONS/GUI/GUI.py```
line 244
 ```computer_name = "Alienware15R3"```
and I was able to launch the KBL GUI correctly

but when trying to change a color or switch the light off. I get the below error on the console

```bash
ERROR from `/usr/share/AlienwareKBL/Bindings.py` on method `_command`:
Command=set_lights, arguments=[bassim,True]
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/Bindings.py", line 54, in _command
    response = getattr(self._pyro, command)(*args)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/core.py", line 171, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/core.py", line 424, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 162, in deserializeData
    return self.loads(data)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 528, in loads
    return self.recreate_classes(serpent.loads(data))
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 399, in recreate_classes
    return self.dict_to_class(literal)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 378, in dict_to_class
    raise Pyro4.errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: usb.core.USBError
```

**Comment by rsm-gh** [comment]
@Hexedheart , that seems weird since actually on archlinux we currently use python-pyro 4.63-1. I'll take a look to that.

**Comment by rsm-gh** [comment]
@TheNetworker thanks for pointing the `"'Configuration.Computers' has no attribute 'Alienware 15R3"` bug, I've fixed it.

Concerning your other problem, I think that it comes from your Pyro version, maybe updating to 4.6+ would fix it

**Comment by Hexedheart** [comment]
@rsm-gh It might have something to do with me being on Kali-rolling but I'm not sure. That's just the best solution I found to the problem as any other attempts just lead to errors.

**Comment by TheNetworker** [comment]
@rsm-gh 
I cloned the new repo (after your modification) and installed the new pyro `pip3 install pyro4==4.63` but still has the same problem

```bash
bassim@me-inside:alienware-kbl$ alienware-kbl                       

(GUI.py:15113): Gtk-WARNING **: Unknown type < define a new column > specified in treemodel liststore_default_blocks

(GUI.py:15113): Gtk-WARNING **: /build/gtk+3.0-Th_a5U/gtk+3.0-3.22.24/./gtk/gtkliststore.c:516: Invalid type (null)

(GUI.py:15113): Gtk-WARNING **: Allocating size to GtkScrolledWindow 0x2448710 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/ADDONS/GUI/GUI.py", line 737, in <module>
    gui = GUI()
  File "/usr/share/AlienwareKBL/ADDONS/GUI/GUI.py", line 245, in __init__
    self.computer = getattr(Computer, computer_name)()```

I think my computer is reporting it's name to be `Alienware 15R3'` but the module is supporting `Alienware15R3'` (without spaces) and that's cause the error

**Comment by rsm-gh** [comment]
@TheNetworker yeah that's the problem, I made the fix [here](https://github.com/rsm-gh/alienware-kbl/commit/e4e46f86d7aac27de6d29a7e7c168703b80b32a0).

Use as root `rm -rf /usr/share/AlienwareKBL` and then download & install the stable branch of alienware-kbl. You should not have that problem anymore.

**Comment by TheNetworker** [comment]
@rsm-gh 
Thanks a lot, this actually solve the problem of `"'Configuration.Computers' has no attribute 'Alienware 15R3" ` but I still have this one when tried to `light off` or change any color from GUI even after upgrade the pyro

```shell
ERROR from `/usr/share/AlienwareKBL/Bindings.py` on method `_command`:
Command=set_lights, arguments=[root,False]
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/Bindings.py", line 54, in _command
    response = getattr(self._pyro, command)(*args)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/core.py", line 187, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/core.py", line 463, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 170, in deserializeData
    return self.loads(data)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 598, in loads
    return self.recreate_classes(serpent.loads(data))
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 415, in recreate_classes
    return self.dict_to_class(literal)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 617, in dict_to_class
    return super(SerpentSerializer, cls).dict_to_class(data)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 394, in dict_to_class
    raise errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: usb.core.USBError



(GUI.py:3238): Gtk-WARNING **: Allocating size to GtkScrolledWindow 0x2f62820 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

```

**Comment by rsm-gh** [comment]
@TheNetworker If using the last version of pyro does not fixe the bug it's gonna be hard to fix since I'm not able of reproducing the bug :/

**Comment by KGMIT** [comment]
I have the exact same problem as the one described in Nov 12 2017 by @TheNetworker starting with Bindings.py's set_lights, and ending up with the usb.core.USBError. Has there been any progress on how to get this issue resolved? I'm happy to debug further if anyone has any potential ideas.

**Comment by TheOmegaPope** [comment]
My Error similar to these is:
ubuntu@ubuntu:~/Downloads/alienware-kbl-stable$ sudo alienware-kbl --start-daemon
ERROR from `/usr/share/AlienwareKBL/Engine/Core/Controller.py` on method `__init__`:
The computer is not supported


Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/Daemon.py", line 394, in <module>
    ConnectDaemon()
  File "/usr/share/AlienwareKBL/Daemon.py", line 42, in __init__
    uri = self.daemon.register(Daemon(self))
  File "/usr/share/AlienwareKBL/Daemon.py", line 55, in __init__
    computer = self._controller.get_computer()
  File "/usr/share/AlienwareKBL/Engine/Core/Controller.py", line 53, in get_computer
    if self._driver.has_device():
AttributeError: 'Controller' object has no attribute '_driver'

Any help would be great

**Comment by rsm-gh** [comment]
Hi @TheOmegaPope  your problem seems to be different:

> ERROR from /usr/share/AlienwareKBL/Engine/Core/Controller.py on method __init__:
> **The computer is not supported**

If you want support please make a new bug report and add all the basic info requested by the bug template (distribution name & version, computer model , etc).

Kind regards

**Comment by Soulsuke** [comment]
Sadly, I'm having this issue as well :<

```
ERROR from `/usr/share/AlienwareKBL/Bindings.py` on method `_command`:
Command=set_lights, arguments=[***,True]
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/Bindings.py", line 54, in _command
    response = getattr(self._pyro, command)(*args)
  File "/usr/lib/python3.6/site-packages/Pyro4/core.py", line 171, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/lib/python3.6/site-packages/Pyro4/core.py", line 424, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "/usr/lib/python3.6/site-packages/Pyro4/util.py", line 162, in deserializeData
    return self.loads(data)
  File "/usr/lib/python3.6/site-packages/Pyro4/util.py", line 528, in loads
    return self.recreate_classes(serpent.loads(data))
  File "/usr/lib/python3.6/site-packages/Pyro4/util.py", line 399, in recreate_classes
    return self.dict_to_class(literal)
  File "/usr/lib/python3.6/site-packages/Pyro4/util.py", line 378, in dict_to_class
    raise Pyro4.errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: usb.core.USBError
```
I have an Alienware 15 R3 as well, and i'm running Arch on it... I've tried with both the stable release and the latest git commit, but the issue is still there. 
As for the installation procedure:
```
# pacman -Suy systemd gksu gtk3 libappindicator-gtk3 python python-cairo python-gobject python-pyusb python-pyro python-pip
# pip install serpent pyro4
# ./setup
```
If I can provide any kind of help (logs, tests, etc) just say it!

**Comment by rsm-gh** [comment]
Hi @Soulsuke, from what I  see the real problem is coming from an USB error. Then pyro is having problems to serialize it, but that's only secondary.

I'd be really curious that you launch the block testing window (`alienware-kbl ----block-testing` as root) and see if you get a log of the real problem. The advantage of using that window is that it doesn't use pyro. We maybe be able to fix it like this :)

**Comment by rsm-gh** [comment]
I'm going to close this bug since I've created [Unable to start the GUI due to Pyro ( unsupported serialized class: usb.core.USBError ) ](https://github.com/rsm-gh/alienware-kbl/issues/40).
